HW1 - Task 1

Kasra Mojallal 110124782

In [1]:
import numpy as np
import plotly.graph_objects as go
from sklearn.linear_model import LinearRegression

In [2]:
# X must have 20 data points and 2 features (as you said in the class)
X = np.random.randn(20, 2)

# for creating the y we can add some randomness to it as eps
eps = np.random.randn(20)

# our y can be a random function containing both of our features and our eps
y = 2*X[:, 0] + 5*X[:, 1] + eps 

In [3]:
# we get the shapes to get a better understanding of our generated data
X.shape, eps.shape, y.shape

((20, 2), (20,), (20,))

In [4]:
# we create a linear regression model using the sk-learn library
model = LinearRegression()

# we fit the model to our X and y
model.fit(X, y)

LinearRegression()

In [5]:
# plotly will be used since it gives us an interactive plot
import plotly.express as px

fig0 = go.Figure(data=go.Scatter3d(
    x=X[:, 0],
    y=X[:, 1],
    z=y,
    mode='markers',
))

fig0.show()

In [6]:
X

array([[ 1.08614932, -0.6261248 ],
       [ 0.96876461,  1.71952109],
       [-0.64719468,  0.4775431 ],
       [-0.83710296,  1.29576378],
       [ 0.76195096,  2.60153644],
       [-1.29125326,  0.55496978],
       [ 0.78735944,  0.39306152],
       [-1.09763771, -1.41066093],
       [ 1.54106828, -0.24781592],
       [-0.81817481,  1.5043541 ],
       [-1.31048924,  0.81594211],
       [-1.46013737, -0.60659391],
       [-1.63571424, -1.19877443],
       [-2.2995393 ,  0.38709484],
       [-0.71125569,  0.83189809],
       [-0.26179911,  0.82564404],
       [-0.39348754, -0.24424258],
       [-0.29153278, -1.1430348 ],
       [ 0.60603113, -0.15205353],
       [-0.70139555,  1.95816955]])

In [7]:
y

array([-0.87827157, 10.63066697,  0.79081304,  4.46016978, 14.44028064,
       -0.09290406,  3.74540109, -9.11434326,  2.15695167,  6.72725466,
        1.15939721, -6.07478479, -9.45853995, -2.3424997 ,  2.37915653,
        4.74284899, -4.22125141, -7.39124774, -0.15293114,  8.9109477 ])

In [8]:
X.min(), X.max()

(-2.2995392973763717, 2.601536443643408)

In [9]:
# we get the minimum and maximum of our data so that we can make a better plot of the regression model
min = X.min()
max = X.max()

# we create a range of our inputs so that we could predict the model for all of those points
# in this case we create a hyper plane of our prediction model
# by adding more numbers the plane would be more accurate but this much is enough
x1_range = np.linspace(min, max, 20)
x2_range = np.linspace(min, max, 20)
x1_grid, x2_grid = np.meshgrid(x1_range, x2_range)

# we predict the values for all of the x_range values using our linear regression model
y_pred = model.predict(np.column_stack((x1_grid.ravel(), x2_grid.ravel())))
y_pred_grid = y_pred.reshape(x1_grid.shape)

In [10]:
# we use plotly go to get a interactive 3D_plot
import plotly.graph_objects as go

# create a 3D plot of our data as we did earlier
fig = go.Figure(data=go.Scatter3d(
    x=X[:, 0],
    y=X[:, 1],
    z=y,
    mode='markers',
))

# create the 3D plot of the regression model on that plot
fig.add_trace(go.Surface(
    x=x1_range,
    y=x2_range,
    z=y_pred_grid,
    colorscale='Viridis',
    opacity=0.8
))

fig.show()

In [11]:
# make predictions of new data
new_data = [[0.65, -0.9]]
model.predict(new_data)

array([-3.59669481])