HW1 - Task 2

Kasra Mojallal 110124782

In [13]:
import numpy as np
import plotly.graph_objects as go

In [14]:
# we create 12 random data points
x = np.random.randn(12)

# we add some randomness with the eps
eps = np.random.randn(12)

# we create the polynomial function of degree 5
y = 2*x + 5*(x**2) -3.5*(x**3) +8*(x**4) + 4.7*(x**5) + eps

In [15]:
x

array([ 1.43996846,  0.01189865, -0.39976323,  0.65966222,  0.20715432,
       -3.83413499,  0.30854358,  1.35404743,  0.07004968,  0.44116515,
       -0.67983451, -0.83393809])

In [16]:
y

array([ 6.67002400e+01,  3.77890538e-01,  5.09761809e-01,  5.13595408e+00,
        6.26453064e-01, -1.90326357e+03,  2.78469553e+00,  5.02842930e+01,
        4.10895033e-01,  1.58488003e+00,  3.82211870e+00,  5.41137669e+00])

In [17]:
# we print the shapes to get a better understanding of the data
x.shape, eps.shape, y.shape

((12,), (12,), (12,))

In [18]:
# we create the plot with plotly.go
data_trace = go.Scatter(x=x, y=y, mode='markers')
fig0 = go.Figure(data=[data_trace])
fig0.show()

In [19]:
from sklearn.preprocessing import PolynomialFeatures

# to create a polynomial regression model we have to use the PolynomialFeatures from sk-learn
# we generate 5 degree of features using this method, we can use linear regression with this features
# following this we can have polynomial regression with just the linear regression model
poly_features = PolynomialFeatures(degree=5)
X_poly = poly_features.fit_transform(x.reshape(-1, 1))

In [20]:
X_poly.shape

(12, 6)

we have 6 features that are:

X to the power of 0, ..., X to the power of 5

In [21]:
from sklearn.linear_model import LinearRegression

# create the same linear regression model and fit it to the data
model_poly = LinearRegression()
model_poly.fit(X_poly, y)

LinearRegression()

In [22]:
min = x.min()
max = x.max()

# we create a range of our inputs so that we could predict the model for all of those points
# in this case we create a line of our prediction model
# by adding more numbers the plane would be more accurate but this much is enough
x_pred = np.linspace(min, max, 100).reshape(-1, 1)
x_pred_grid = poly_features.fit_transform(x_pred)

# y_pred is the prediction of the poly_model for the 100 points
y_pred = model_poly.predict(x_pred_grid)

In [23]:
# we create a plot having the data and the polynomial model
data_trace = go.Scatter(x=x.flatten(), y=y, mode='markers')
prediction_trace = go.Scatter(x=x_pred.flatten(), y=y_pred, mode='lines')

fig = go.Figure(data=[data_trace, prediction_trace])
fig.show()

In [12]:
# we can make predictions on new data as well
x_test = np.array([-0.45, 1.1])
x_test = poly_features.fit_transform(x_test.reshape(-1, 1))

predictions = model_poly.predict(x_test)
predictions

array([ 0.14492514, 21.09210888])